cors:
  originsPatterns: "http://localhost:8080, http://localhost:3000"

file:
  upload-dir: /Users/joaqu/Documents
spring:
  application:
    name: crud1
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/crud1?useTimezone=true&serverTimezone=UTC
    username: root
    password: Joaquim10@@
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false

  logging:
    level:
      br.com.joaquim.crud1: INFO

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 200MB


  spring-doc:
    paths-to-match: /api/**/v1/**
    swagger-ui:
      use-root-path: true